@startuml

'
' ==========================
'  Fetcher des requêtes
' ==========================
interface RequestFetcher {
    + fetchRequest(): str
}

class HttpRequestFetcher implements RequestFetcher {
    + fetchRequest(payload : str): str
}

'
' ==========================
'  Le Contrôleur
' ==========================
class LoadingController {
 		- requestFetcher: IRequestFetcher
    - serializer: IJsonSerializer
    - databaseClient: IDatabaseClient
    + handleRequest(payload: str): str
}

'
' ==========================
'  La Sérialisation
' ==========================
interface JsonSerializer {
    + serialize(jsonData: str)
}

class StationSerializer implements JsonSerializer {
    + serialize(jsonData: str): Station
    - parseRaw(jsonData: str): Station
}

note bottom of StationSerializer
  Utilise Pydantic pour désérialiser
  le JSON en un objet Station
  (avec ses Departures et Trains).
end note

'
' ==========================
'  Domain Objects
' ==========================
interface BaseModel
note left of BaseModel
  Classe de base Pydantic
end note

class Station extends BaseModel {
    - name: str
    - departures: List<Departure>
}

class Departure extends BaseModel {
    - departureStationName: str
    - destinationStationName: str
    - viaStationName: Optional[str]
    - departureTime: datetime
    - platform: str
    - sector: str
    - trains: List<Train>
}

class Train extends BaseModel {
    - type: str
    - number: str
}

'
' ==========================
'  Services et Persistance
' ==========================

interface DatabaseClient {
		+ client()
    + insert(): void
    + update(): void
    + exist(): bool
}

class PostgresClient implements DatabaseClient {
		+ postgresClient()
    + insert(station: Station): void
    + update(station: Station): void
    + exist(name: str): bool
}

class AWSSDK{}

'
' ==========================
' Gestion des erreurs
' ==========================

interface Error {}

class BadRequestError implements Error {
		+ message: str
}

class ForbiddenError implements Error {
		+ message: str
}

class HttpExeption implements Error{
		+ message: str
}

class InternalServerError implements Error {
		+ message: str
}

class NotFoundError implements Error {
		+ message: str
}

class UnauthorizedError implements Error {
		+ message: str
}

'
' ==========================
' Relations
' ==========================
LoadingController -right-* RequestFetcher
LoadingController --* JsonSerializer
LoadingController -left-* DatabaseClient
StationSerializer -down-> Station
PostgresClient -> AWSSDK
LoadingController --.> Error


@enduml
